global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'vocal-webhook'

receivers:
  - name: 'vocal-webhook'
    webhook_configs:
      - url: 'http://host.docker.internal:5000/alert'
        send_resolved: false