groups:
  - name: server_alerts
    rules:

      - alert: ServeurHorsLigne
        expr: up{job="servers"} == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Serveur hors ligne : {{ $labels.instance }}"
          description: "Le serveur {{ $labels.instance }} ne répond plus."

      - alert: CPUHigh
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "CPU élevé sur {{ $labels.instance }}"
          description: "CPU à {{ $value | printf \"%.1f\" }}%"

      - alert: RAMHigh
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "RAM élevée sur {{ $labels.instance }}"
          description: "RAM à {{ $value | printf \"%.1f\" }}%"